# Generated by Django 5.1.7 on 2025-04-14 10:08

import django.db.models.deletion
import storage.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('stored_file', models.FileField(upload_to=storage.models.user_directory_path)),
                ('size', models.BigIntegerField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('last_download', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('special_link', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file_hash', models.CharField(default=None, editable=False, max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
