# version: '3.9'

networks:
  mycloud-network:
    driver: bridge

services:
  db:
    image: postgres:15-alpine
    container_name: mycloud_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mycloud_admin
      POSTGRES_PASSWORD: 5tr0ngP@ss
      POSTGRES_DB: mycloud_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mycloud-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mycloud_admin -d mycloud_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./
    container_name: mycloud_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 --workers 3 backend.wsgi"
    volumes:
      - backend_static:/app/static
      - backend_media:/app/media
    networks:
      - mycloud-network
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  backend_static:
  backend_media:
